put merged local readme content to top of remote readme
There was a readme.md file in my local. When I was pulling the changes to the local repo from remote repo i.e this 'makeAndSellBurger', then it was no allowing me to do so.  I was getting below error : 

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master)
$ git pull origin master --allow-unrelated-histories
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (2/2), done.
From https://github.com/fs-projects/makeAndSellBurger
 * branch            master     -> FETCH_HEAD
   9ec5d3c..12a3e18  master     -> origin/master
CONFLICT (modify/delete): README.md deleted in 12a3e18abdea8b2cb97974538518ac115ea7197f and modified in HEAD. Version HEAD of README.md left in tree.
Automatic merge failed; fix conflicts and then commit the result.

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master|MERGING)
$ git pull origin master --allow-unrelated-histories
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

To solve above I did below : 

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master|MERGING)
$ git status
On branch master
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by them: README.md

no changes added to commit (use "git add" and/or "git commit -a")

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master|MERGING)
$ git add .

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master|MERGING)
$ git merge origin
fatal: You have not concluded your merge (MERGE_HEAD exists).
Please, commit your changes before you merge.

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master|MERGING)
$ git commit -m 'solve the umerged path'
[master caca69d] solve the umerged path

After above see below : 

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master)
$ git pull origin master --allow-unrelated-histories
From https://github.com/fs-projects/makeAndSellBurger
 * branch            master     -> FETCH_HEAD
Already up to date.

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master)
$ git push origin master
Enumerating objects: 123, done.
Counting objects: 100% (123/123), done.
Delta compression using up to 4 threads
Compressing objects: 100% (112/112), done.
Writing objects: 100% (120/120), 204.85 KiB | 1.95 MiB/s, done.
Total 120 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), done.
To https://github.com/fs-projects/makeAndSellBurger.git
   12a3e18..caca69d  master -> master

Utkarsh Kukreti@DESKTOP-5U0MEA4 MINGW64 /d/Full Stack/React JS/the_burger_builder_project (master)
$ git status
On branch master
nothing to commit, working tree clean